AWSTemplateFormatVersion: 2010-09-09

Parameters:

  KeyAlias:
    Type: String

Resources:

  DefaultKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Used by Assumed Roles in Dev/Test/Prod accounts to Encrypt/Decrypt code
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Allows key administration
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: "kms:*"
            Resource: "*"

  DefaultKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${KeyAlias}-key
      TargetKeyId: !Ref DefaultKmsKey

Outputs:

  DefaultKeyId:
    Value: !Ref DefaultKmsKey
