site_name: Flexli Engine (Alpha)
site_description: Flexli Engine (Alpha)
#site_url: http://localhost

docs_dir: docs/user_guide/
site_dir: build/docs/

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API Quickstart: api_quickstart.md
  - Authoring:
    - Expressions: authoring/expressions.md
    - Connectors: authoring/connectors.md
    - Workflows: authoring/workflows.md
    - Core Resources: authoring/core.md
    - Workflow Strategies: authoring/strategies.md
    - Templates: authoring/templates.md
    - Working with Editors: authoring/editors.md
#  - API Docs: "./api"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep-purple
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep-purple
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
