AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:

  LogLevel:
    Type: String
    AllowedValues:
      - DEBUG
      - INFO
    Default: INFO

  AppDomain:
    Type: String
    MinLength: 3

  SubDomain:
    Type: String
    MinLength: '3'
    MaxLength: '63'
    AllowedPattern: ^[a-z0-9][a-z0-9\-]{1,61}[a-z0-9]$

  HostedZoneId:
    Type: String

  CertificateArn:
    Type: String
    Description: Must be us-east-1

Resources:

  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref AWS::StackName
      ContentUri: ./src/layers/layer
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10
      BuildArchitecture: arm64

  DefaultKeys:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/default_keys/template.yaml
      Parameters:
        KeyAlias: !Ref AWS::StackName

  Resources:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/resources/template.yaml
      Parameters:
        LogLevel: !Ref LogLevel
        SharedLayerArn: !Ref Layer
        DefaultKeyId: !GetAtt DefaultKeys.Outputs.DefaultKeyId

  Auth:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/auth/template.yaml
      Parameters:
        AppDomain: !Ref AppDomain
        SubDomain: !Ref SubDomain
        HostedZoneId: !Ref HostedZoneId
        CertificateArn: !Ref CertificateArn

  WorkflowsApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/workflows_api/template.yaml
      Parameters:
        LogLevel: !Ref LogLevel
        SharedLayerArn: !Ref Layer
        DefaultKeyId: !GetAtt DefaultKeys.Outputs.DefaultKeyId
        MainTableName: !GetAtt Resources.Outputs.MainTableName
        WorkflowHistoryV1TableName: !GetAtt Resources.Outputs.WorkflowHistoryV1TableName
        RunQueueName: !GetAtt Resources.Outputs.RunQueueName
        RunQueueUrl: !GetAtt Resources.Outputs.RunQueueUrl
        CognitoUserPoolArn: !GetAtt Auth.Outputs.CognitoUserPoolArn
        AppDomain: !Ref AppDomain
        HostedZoneId: !Ref HostedZoneId
        CertificateArn: !Ref CertificateArn

  WorkflowsScheduler:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./src/workflows_scheduler/template.yaml
      Parameters:
        LogLevel: !Ref LogLevel
        SharedLayerArn: !Ref Layer
        MainTableName: !GetAtt Resources.Outputs.MainTableName
        MainTableEventBusName: !GetAtt Resources.Outputs.MainTableEventBusName
        RunQueueName: !GetAtt Resources.Outputs.RunQueueName
        RunQueueUrl: !GetAtt Resources.Outputs.RunQueueUrl

Outputs:

  MainTableName:
    Description: Name of DynamoDB Table
    Value: !GetAtt Resources.Outputs.MainTableName

  WorkflowHistoryV1TableName:
    Value: !GetAtt Resources.Outputs.WorkflowHistoryV1TableName

  CognitoUserPoolSignIn:
    Description: The sign-in URL of the Cognito User Pool for authentication
    Value: !GetAtt Auth.Outputs.CognitoUserPoolSignIn

  WorkflowsApiEndpoint:
    Value: !GetAtt WorkflowsApi.Outputs.WorkflowsApiEndpoint
