data = {
    "event": {"jssID": 1, "username": "bryson"},
    "webhook": {
        "eventTimestamp": 1689534040,
        "id": 1,
        "name": "string",
        "webhookEvent": "ComputerInventoryCompleted",
    },
    "installed_apps": [
        {
            "name": "Freeform.app",
            "path": "/System/Applications/Freeform.app",
            "version": "1.2",
            "macAppStore": False,
            "sizeMegabytes": 21,
            "bundleId": "com.apple.freeform",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Messages.app",
            "path": "/System/Applications/Messages.app",
            "version": "14.0",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.MobileSMS",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "FindMy.app",
            "path": "/System/Applications/FindMy.app",
            "version": "4.0",
            "macAppStore": False,
            "sizeMegabytes": 20,
            "bundleId": "com.apple.findmy",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Automator.app",
            "path": "/System/Applications/Automator.app",
            "version": "2.10",
            "macAppStore": False,
            "sizeMegabytes": 4,
            "bundleId": "com.apple.Automator",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Reminders.app",
            "path": "/System/Applications/Reminders.app",
            "version": "7.0",
            "macAppStore": False,
            "sizeMegabytes": 13,
            "bundleId": "com.apple.reminders",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Mail.app",
            "path": "/System/Applications/Mail.app",
            "version": "16.0",
            "macAppStore": False,
            "sizeMegabytes": 14,
            "bundleId": "com.apple.mail",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Clock.app",
            "path": "/System/Applications/Clock.app",
            "version": "1.0",
            "macAppStore": False,
            "sizeMegabytes": 5,
            "bundleId": "com.apple.clock",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Stickies.app",
            "path": "/System/Applications/Stickies.app",
            "version": "10.2",
            "macAppStore": False,
            "sizeMegabytes": 1,
            "bundleId": "com.apple.Stickies",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Digital Color Meter.app",
            "path": "/System/Applications/Utilities/Digital Color Meter.app",
            "version": "5.22",
            "macAppStore": False,
            "sizeMegabytes": 1,
            "bundleId": "com.apple.DigitalColorMeter",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Screenshot.app",
            "path": "/System/Applications/Utilities/Screenshot.app",
            "version": "1.0",
            "macAppStore": False,
            "sizeMegabytes": 0,
            "bundleId": "com.apple.screenshot.launcher",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Home.app",
            "path": "/System/Applications/Home.app",
            "version": "7.0",
            "macAppStore": False,
            "sizeMegabytes": 6,
            "bundleId": "com.apple.Home",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "VoiceOver Utility.app",
            "path": "/System/Applications/Utilities/VoiceOver Utility.app",
            "version": "10",
            "macAppStore": False,
            "sizeMegabytes": 5,
            "bundleId": "com.apple.VoiceOverUtility",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Terminal.app",
            "path": "/System/Applications/Utilities/Terminal.app",
            "version": "2.13",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.Terminal",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Safari.app",
            "path": "/Applications/Safari.app",
            "version": "16.5.1",
            "macAppStore": False,
            "sizeMegabytes": 12,
            "bundleId": "com.apple.Safari",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "TextEdit.app",
            "path": "/System/Applications/TextEdit.app",
            "version": "1.18",
            "macAppStore": False,
            "sizeMegabytes": 2,
            "bundleId": "com.apple.TextEdit",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Contacts.app",
            "path": "/System/Applications/Contacts.app",
            "version": "2539.10",
            "macAppStore": False,
            "sizeMegabytes": 6,
            "bundleId": "com.apple.AddressBook",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Photo Booth.app",
            "path": "/System/Applications/Photo Booth.app",
            "version": "13.0",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.PhotoBooth",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Podcasts.app",
            "path": "/System/Applications/Podcasts.app",
            "version": "1.1.0",
            "macAppStore": False,
            "sizeMegabytes": 19,
            "bundleId": "com.apple.podcasts",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Chess.app",
            "path": "/System/Applications/Chess.app",
            "version": "3.18",
            "macAppStore": False,
            "sizeMegabytes": 5,
            "bundleId": "com.apple.Chess",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Weather.app",
            "path": "/System/Applications/Weather.app",
            "version": "3.3.1",
            "macAppStore": False,
            "sizeMegabytes": 12,
            "bundleId": "com.apple.weather",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Disk Utility.app",
            "path": "/System/Applications/Utilities/Disk Utility.app",
            "version": "22.6",
            "macAppStore": False,
            "sizeMegabytes": 4,
            "bundleId": "com.apple.DiskUtility",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Activity Monitor.app",
            "path": "/System/Applications/Utilities/Activity Monitor.app",
            "version": "10.14",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.ActivityMonitor",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Calculator.app",
            "path": "/System/Applications/Calculator.app",
            "version": "10.16",
            "macAppStore": False,
            "sizeMegabytes": 2,
            "bundleId": "com.apple.calculator",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Mission Control.app",
            "path": "/System/Applications/Mission Control.app",
            "version": "1.2",
            "macAppStore": False,
            "sizeMegabytes": 0,
            "bundleId": "com.apple.exposelauncher",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Photos.app",
            "path": "/System/Applications/Photos.app",
            "version": "8.0",
            "macAppStore": False,
            "sizeMegabytes": 22,
            "bundleId": "com.apple.Photos",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Image Capture.app",
            "path": "/System/Applications/Image Capture.app",
            "version": "8.0",
            "macAppStore": False,
            "sizeMegabytes": 2,
            "bundleId": "com.apple.Image_Capture",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "TV.app",
            "path": "/System/Applications/TV.app",
            "version": "1.3.5",
            "macAppStore": False,
            "sizeMegabytes": 44,
            "bundleId": "com.apple.TV",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "System Settings.app",
            "path": "/System/Applications/System Settings.app",
            "version": "15.0",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.systempreferences",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "FaceTime.app",
            "path": "/System/Applications/FaceTime.app",
            "version": "5.0",
            "macAppStore": False,
            "sizeMegabytes": 7,
            "bundleId": "com.apple.FaceTime",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Books.app",
            "path": "/System/Applications/Books.app",
            "version": "5.2",
            "macAppStore": False,
            "sizeMegabytes": 43,
            "bundleId": "com.apple.iBooksX",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "AirPort Utility.app",
            "path": "/System/Applications/Utilities/AirPort Utility.app",
            "version": "6.3.9",
            "macAppStore": False,
            "sizeMegabytes": 22,
            "bundleId": "com.apple.airport.airportutility",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Dictionary.app",
            "path": "/System/Applications/Dictionary.app",
            "version": "2.3.0",
            "macAppStore": False,
            "sizeMegabytes": 13,
            "bundleId": "com.apple.Dictionary",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Boot Camp Assistant.app",
            "path": "/System/Applications/Utilities/Boot Camp Assistant.app",
            "version": "6.1.0",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.bootcampassistant",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Notes.app",
            "path": "/System/Applications/Notes.app",
            "version": "4.10",
            "macAppStore": False,
            "sizeMegabytes": 15,
            "bundleId": "com.apple.Notes",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Font Book.app",
            "path": "/System/Applications/Font Book.app",
            "version": "11.0",
            "macAppStore": False,
            "sizeMegabytes": 6,
            "bundleId": "com.apple.FontBook",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Bluetooth File Exchange.app",
            "path": "/System/Applications/Utilities/Bluetooth File Exchange.app",
            "version": "9.0",
            "macAppStore": False,
            "sizeMegabytes": 2,
            "bundleId": "com.apple.BluetoothFileExchange",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Audio MIDI Setup.app",
            "path": "/System/Applications/Utilities/Audio MIDI Setup.app",
            "version": "3.5",
            "macAppStore": False,
            "sizeMegabytes": 4,
            "bundleId": "com.apple.audio.AudioMIDISetup",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Grapher.app",
            "path": "/System/Applications/Utilities/Grapher.app",
            "version": "2.7",
            "macAppStore": False,
            "sizeMegabytes": 5,
            "bundleId": "com.apple.grapher",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "System Information.app",
            "path": "/System/Applications/Utilities/System Information.app",
            "version": "11.0",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.SystemProfiler",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Siri.app",
            "path": "/System/Applications/Siri.app",
            "version": "1.0",
            "macAppStore": False,
            "sizeMegabytes": 2,
            "bundleId": "com.apple.siri.launcher",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Music.app",
            "path": "/System/Applications/Music.app",
            "version": "1.3.5",
            "macAppStore": False,
            "sizeMegabytes": 56,
            "bundleId": "com.apple.Music",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "QuickTime Player.app",
            "path": "/System/Applications/QuickTime Player.app",
            "version": "10.5",
            "macAppStore": False,
            "sizeMegabytes": 4,
            "bundleId": "com.apple.QuickTimePlayerX",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Migration Assistant.app",
            "path": "/System/Applications/Utilities/Migration Assistant.app",
            "version": "13.4",
            "macAppStore": False,
            "sizeMegabytes": 1,
            "bundleId": "com.apple.MigrateAssistant",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Calendar.app",
            "path": "/System/Applications/Calendar.app",
            "version": "13.0",
            "macAppStore": False,
            "sizeMegabytes": 6,
            "bundleId": "com.apple.iCal",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Time Machine.app",
            "path": "/System/Applications/Time Machine.app",
            "version": "1.3",
            "macAppStore": False,
            "sizeMegabytes": 1,
            "bundleId": "com.apple.backup.launcher",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "News.app",
            "path": "/System/Applications/News.app",
            "version": "8.4",
            "macAppStore": False,
            "sizeMegabytes": 4,
            "bundleId": "com.apple.news",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "App Store.app",
            "path": "/System/Applications/App Store.app",
            "version": "3.0",
            "macAppStore": False,
            "sizeMegabytes": 9,
            "bundleId": "com.apple.AppStore",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Script Editor.app",
            "path": "/System/Applications/Utilities/Script Editor.app",
            "version": "2.11",
            "macAppStore": False,
            "sizeMegabytes": 2,
            "bundleId": "com.apple.ScriptEditor2",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Keychain Access.app",
            "path": "/System/Applications/Utilities/Keychain Access.app",
            "version": "11.0",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.keychainaccess",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "VoiceMemos.app",
            "path": "/System/Applications/VoiceMemos.app",
            "version": "2.3",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.VoiceMemos",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Stocks.app",
            "path": "/System/Applications/Stocks.app",
            "version": "5.3.1",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.stocks",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Maps.app",
            "path": "/System/Applications/Maps.app",
            "version": "3.0",
            "macAppStore": False,
            "sizeMegabytes": 42,
            "bundleId": "com.apple.Maps",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "ColorSync Utility.app",
            "path": "/System/Applications/Utilities/ColorSync Utility.app",
            "version": "12.0.0",
            "macAppStore": False,
            "sizeMegabytes": 3,
            "bundleId": "com.apple.ColorSyncUtility",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Preview.app",
            "path": "/System/Applications/Preview.app",
            "version": "11.0",
            "macAppStore": False,
            "sizeMegabytes": 5,
            "bundleId": "com.apple.Preview",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Launchpad.app",
            "path": "/System/Applications/Launchpad.app",
            "version": "1.0",
            "macAppStore": False,
            "sizeMegabytes": 1,
            "bundleId": "com.apple.launchpad.launcher",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Console.app",
            "path": "/System/Applications/Utilities/Console.app",
            "version": "1.1",
            "macAppStore": False,
            "sizeMegabytes": 1,
            "bundleId": "com.apple.Console",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
        {
            "name": "Shortcuts.app",
            "path": "/System/Applications/Shortcuts.app",
            "version": "6.0",
            "macAppStore": False,
            "sizeMegabytes": 2,
            "bundleId": "com.apple.shortcuts",
            "updateAvailable": False,
            "externalVersionId": "0",
        },
    ],
    "installed_certs": [
        {
            "commonName": "com.apple.systemdefault",
            "identity": True,
            "expirationDate": "2043-07-10T16:23:20Z",
            "username": None,
            "lifecycleStatus": "ACTIVE",
            "certificateStatus": "ISSUED",
            "subjectName": "CN=com.apple.systemdefault,O=System Identity",
            "serialNumber": "105275409",
            "sha1Fingerprint": "15fd2791e3ef65abfbfc65ffa2ff2ef7b42f18eb",
            "issuedDate": "2023-07-15T16:23:20Z",
        },
        {
            "commonName": "Side7 LLC JSS Built-in Certificate Authority",
            "identity": False,
            "expirationDate": "2033-06-19T14:19:11Z",
            "username": None,
            "lifecycleStatus": "ACTIVE",
            "certificateStatus": "ISSUED",
            "subjectName": "CN=Side7 LLC JSS Built-in Certificate Authority",
            "serialNumber": "2288865790",
            "sha1Fingerprint": "8cbc25b5aa0b41af24cfaa3c98819f1b38941fb1",
            "issuedDate": "2023-06-18T14:19:11Z",
        },
        {
            "commonName": "D9E30187-9E39-4BC5-B47D-81A3933B3B73",
            "identity": True,
            "expirationDate": "2025-07-15T17:03:47Z",
            "username": None,
            "lifecycleStatus": "ACTIVE",
            "certificateStatus": "ISSUED",
            "subjectName": "CN=D9E30187-9E39-4BC5-B47D-81A3933B3B73,O=Side7 LLC",
            "serialNumber": "789166655",
            "sha1Fingerprint": "84327fcd4e07fdf76c06926b1a82b472c842dd64",
            "issuedDate": "2023-07-14T17:03:47Z",
        },
        {
            "commonName": "com.apple.kerberos.kdc",
            "identity": True,
            "expirationDate": "2043-07-10T16:23:21Z",
            "username": None,
            "lifecycleStatus": "ACTIVE",
            "certificateStatus": "ISSUED",
            "subjectName": "CN=com.apple.kerberos.kdc,O=System Identity",
            "serialNumber": "1708119284",
            "sha1Fingerprint": "922ee58c671800313913afac4cf7568d7e228aeb",
            "issuedDate": "2023-07-15T16:23:21Z",
        },
    ],
}

from transforms import find_values_dict, find_and_format_strings


def test_find_values_dict():
    result = find_values_dict(
        {
            "username": "::event.username",
            "computer_id": "::event.jssID",
            "application_count": "::installed_apps[] | length(@)",
            "certificate_count": "::installed_certs[] | length(@)",
        },
        data,
    )
    assert result == {
        "application_count": 57,
        "certificate_count": 4,
        "computer_id": 1,
        "username": "bryson",
    }


def test_one():
    source = {
        "text": "Computer Inventory Update ({computer_id} - {username})",
        "blocks": [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "Hello, world!"},
            },
            {"type": "divider"},
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": "Number of installed applications: *{application_count}*",
                    },
                    {
                        "type": "mrkdwn",
                        "text": "Number of installed certificates: *{certificate_count}*",
                    },
                ],
            },
        ],
    }

    find_and_format_strings(
        target=source,
        format_vars={
            "application_count": 57,
            "certificate_count": 4,
            "computer_id": 1,
            "username": "bryson",
        },
    )

    print(source)
    assert source == {
        "text": "Computer Inventory Update (1 - bryson)",
        "blocks": [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "Hello, world!"},
            },
            {"type": "divider"},
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": "Number of installed applications: *57*",
                    },
                    {
                        "type": "mrkdwn",
                        "text": "Number of installed certificates: *4*",
                    },
                ],
            },
        ],
    }
