name: Publish Documentation

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pipenv
          pipenv sync --dev --system --verbose

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build Docs
        run: |
          mkdocs build
          # ./write_openapi_schemas.py
          # Temporary workaround
          mkdir build/docs/_schemas/
          cp docs/api/_schemas/*.json build/docs/_schemas
          mkdir build/docs/api/
          cp docs/api/index.html build/docs/api

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/docs/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
